"""Many-to-many relationship

Revision ID: bdc241d9cc0f
Revises: 0262106abb55
Create Date: 2021-12-11 17:43:11.981949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc241d9cc0f'
down_revision = '0262106abb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('studentID', sa.Integer(), nullable=True),
    sa.Column('moduleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moduleID'], ['module.id'], ),
    sa.ForeignKeyConstraint(['studentID'], ['student.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
